### ISSUE TITLE
Tour in IE8

### ISSUE THREAD

**Issue by wouterterlouw** [quintel/etflex#412]
![dashboard-3](https://f.cloud.github.com/assets/4319656/2007808/a299c824-873d-11e3-9d02-3ab9ea870fcc.jpg)

**Comment by jorisberkhout** [comment]
@grdw told me that we do no longer support IE8 for ETModel (see https://github.com/quintel/etmodel/pull/1978). I assume this goes for ETFlex as well.

Shall we consider this issue solved, @dennisschoenmakers ?
