### ISSUE TITLE
Question: Should we turn on the merit order in ETFlex?

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etflex#421]
While playing the 3D game, someone pointed out to me that there is an apparent inconsistency between the reliability and the balance between demand and supply. In the start scenario (all sliders set to `0`), there is a large difference between demand and supply (`~ 160 PJ`) but the reliability is still `78%`. If you build 4 more gas plants, the difference between demand and supply is still `~140 PJ`, but the reliability is `100%`. This has to do with the fact that the supply takes into account the full load hours of a plant (and these are rather low for NL/2011), while the reliability is based on production capacity. So, even though there is enough capacity to meet the demand, the low full load hours prevent this from happening. This problem would be solved by turning on the merit order. The downside would be that you only need 1 or 2 moves to balance demand and supply. In addition, the game might become slower if we turn on the merit order.

How do you feel about this, @AlexanderWirtz , @ChaelKruip and @dennisschoenmakers ?

**Comment by jorisberkhout** [comment]
As a result of turning the merit order on for the default scenario (see https://github.com/quintel/etmodel/issues/2017), the merit order is now also turned on in ETFlex. This does change the nature of the game, which I personally quite like. The emphasis of the game is no longer on simply balancing demand and supply, but more on making the current NL energy system more renewable and lower the CO2-emissions, while you have to keep an eye on the reliability and costs. I think this is much closer to the current debate on the future of the NL energy system.

Please re-open if you disagree with the changes.

**Comment by dennisschoenmakers** [comment]
When demo'ing ETFlex with the Merit Order now turned off, I am not convinced that turning on the Merit Order for ETFlex is a good thing. I am kind of lost what the game is about now. And it is confusing (for laymen at least) that supply now decreased when I am reducing my supply. The whole game was about balancing supply and demand, right? 

So, I am boldly reopening this discussion. :smile:

**Comment by jorisberkhout** [comment]
After playing around with ETFlex, I fully agree with @dennisschoenmakers . Let's switcht the merit order off again for ETFlex. Could you do this @dennisschoenmakers ?

**Comment by dennisschoenmakers** [comment]
@antw could you have a look at this please?
