### ISSUE TITLE
ETFlex level 2 does not load

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etflex#436]
![energy_transition_model_light](https://cloud.githubusercontent.com/assets/1303760/11898248/c2d62d7a-a596-11e5-874b-070e12806349.png)

**Comment by antw** [comment]
It uses the old add-on heat-pump. Will fix.

**Comment by ChaelKruip** [comment]
I think we fixed that with https://github.com/quintel/etflex/commit/f05c3d1027e865c123922fd3c7f72e05a60a5028 right?

**Comment by antw** [comment]
Aaaand... deployed. :innocent:
