### ISSUE TITLE
Image/file for electric car info text not displayed, 404 not found

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etflex#437]
![screen shot 2016-02-08 at 16 30 30](https://cloud.githubusercontent.com/assets/14106387/12889933/92dc5cb6-ce81-11e5-8565-65eff856f635.png)

File not displayed, gives a 404 not found.

Re-assign at will.

**Comment by jorisberkhout** [comment]
Assigning @grdw to look into this.

**Comment by marliekeverweij** [comment]
![Screen Shot 2019-03-15 at 16 58 29](https://user-images.githubusercontent.com/32833996/54444694-9635cd00-4743-11e9-9029-162e2ce0209f.png)
