### ISSUE TITLE
When going over the dashboard with your cursor, another question mark sign appears

### ISSUE THREAD

**Issue by RobTerwel** [quintel/etflex#438]
![screen shot 2016-02-08 at 16 21 57](https://cloud.githubusercontent.com/assets/14106387/12889982/d5fab24a-ce81-11e5-8da1-f379d40cfa2c.png)

Not sure if this is intentional or not, but these question marks appear at fixed positions when hoovering your cursor over the relevant dashboard icon.

Re-assign at will.

**Comment by jorisberkhout** [comment]
Assigning @grdw .
