### ISSUE TITLE
ETFlex not working on Live and Beta server

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etflex#440]
As discussed with @grdw , this is likely due to the fact that `(beta.)et-engine.com` has been renamed to `(beta-)engine.energytransitionmodel.com`, see screenshots below.

<img width="804" alt="screen shot 2016-04-01 at 11 16 10" src="https://cloud.githubusercontent.com/assets/4669028/14202997/9709ae44-f7fb-11e5-9611-ad3685c87a86.png">

<img width="857" alt="screen shot 2016-04-01 at 11 17 27" src="https://cloud.githubusercontent.com/assets/4669028/14202998/970ce01e-f7fb-11e5-8b47-dd5b13dbbdc2.png">

**Comment by grdw** [comment]
I changed ansible and the sample configuration file in etflex accordingly. I changed the configuration on live and staging by hand and restarted the rails process. And it's working again:

![screen shot 2016-04-01 at 11 43 40](https://cloud.githubusercontent.com/assets/2676542/14203557/0233501e-f7ff-11e5-8e33-3dd49378d60e.png)

**Comment by dennisschoenmakers** [comment]
:+1: Thanks @grdw
