### ISSUE TITLE
Running Etflex on game specific id's

### ISSUE THREAD

**Issue by SergenN** [quintel/etflex#447]
Currently when Etflex starts it connects to the channel defined by the 'env' variable. Our idea was to change this into a game id specific to the beagle-bone. On the server side we have already made changes to handle multiple pusher channels and we have thought about a way to get the correct game id to the related Etflex game. Eventually we ended up with an idea to add a parameter to the URL for example

> et-model.com/scenes/:id**/game/:gid**/with/:wid 

Since Etflex adds it's own game id to the url we figured that we would have to adjust the method which adds the /with/ parameter. If i am not mistaken this happens in the main.coffee class and specifically in the startScene method? Now the problem is that we could not figure out how the method works since the Coffeescript syntax unknown to us. So our question; how can we tackle the problem of adding a parameter to the game?

@grdw

**Comment by grdw** [comment]
> Currently when Etflex starts it connects to the channel defined by the 'env' variable
> Our idea was to change this into a game id specific to the beagle-bone

👍 

> If i am not mistaken this happens in the main.coffee class
> [..] specifically in the startScene method?

Yes.  [These](https://github.com/quintel/etflex/blob/master/client/routers/main.coffee#L33-L36) are the relevant lines. SceneView is defined [here](https://github.com/quintel/etflex/blob/master/client/views/scene.coffee#L24). 

> how can we tackle the problem of adding a parameter to the game?

I am not sure what you mean with 'adding a parameter'? Could you elaborate that a little.

If I get it correctly you can support multiple pusher channels but the ETFlex games are not using the same channels?

**Comment by grdw** [comment]
Okay, from the meeting we had a thing or two become more clear to me. It's in [here](https://github.com/quintel/etflex/blob/master/config/routes.rb#L3-L9) where you want to edit the extra argument in the url.

So this could look like (in order to become `/games/:game_id/with/:id`) :

```ruby
resources :scenes, except: %w( new create edit update destroy ) do
  # Pseudo code:  
  resources :games, only: %w (show ) do
    post 'with/:id', to: 'scenarios#update'    
  end
  # End of pseudo code
  
  get  'with/:id', to: 'scenarios#show', as: :scenario
  post 'with/:id', to: 'scenarios#update'
  put  'with/:id', to: 'scenarios#update'

  member { get 'fresh' }
end
```
