### ISSUE TITLE
Unknown error (status code 403): API call failed since (daily) message quota exceeded 

### ISSUE THREAD

**Issue by grdw** [quintel/etflex#448]
![screen shot 2017-09-07 at 12 07 57](https://user-images.githubusercontent.com/2676542/30158336-3e962d02-93c5-11e7-852e-e1415da8aa31.png)

This is odd. Is ETFlex actually in use by anybody?

**Comment by grdw** [comment]
Turns out some people at TU delft are causing the havoc. 

Don't know how the meter all of a sudden went to 200K within hours 😆

**Comment by antw** [comment]
Happens every now and again when it gets busy (I guess during a workshop). It's not really a big problem; the only effect is that the scoreboard stops updating in real-time, and the rest of the app is unaffected.
