### ISSUE TITLE
Increasing green gas % to 10% should lower the CO2-emissions for the player. 

### ISSUE THREAD

**Issue by MartLubben** [quintel/etflex#449]
A higher % of green gas should lower the CO2-emissions. However from the Mechanical turk it became clear that this is not happening. For the player it is unclear why, because the reason is quite complex. 

**The reason:**
A higher % of green gas increases the gas price, imported electricity is cheaper and creates a shift in the merit order, import has higher CO2-emissions by default and this results in higher CO2-emissions. 

**The solution:** 
A high import price could be a solution.
No merit order could be a solution. 
A low biomass price could be a solution. 

@antw What would be the best solution do you think?

**Comment by ChaelKruip** [comment]
> @antw What would be the best solution do you think?

I'll take this one if you don't mind @MartLubben 😄 
Setting the import price higher than the highest marginal cost will change the behaviour of the game back to what was intended. The other options might have other unwanted fallout.
