### ISSUE TITLE
When adjusting solar or wind in the 'balance energy demand and supply' game nothing happen to the emissions, this is counterintuitive

### ISSUE THREAD

**Issue by Charlottevm** [quintel/etflex#485]
We got a question from an energy game user (game 1) about the lack of change in emissions when increasing solar or wind. 

If solar or wind power are increased this does not decrease emissions: 

![afbeelding](https://user-images.githubusercontent.com/74194356/120309991-2d13e300-c2d6-11eb-99d9-96e617fa59b5.png)
![afbeelding](https://user-images.githubusercontent.com/74194356/120310003-30a76a00-c2d6-11eb-9a18-bdd3d61f7cdc.png)

The reason nothing happens is because there is no electricity supply or electricity import when starting the game, and therefore also no emissions are attributed to electricity supply which explains why nothing happens when you add supply. This is counterintuitive because:
- We do take the existing heat supply and emissions into account 
- Users expect to reduce their emissions by increasing renewable electricity supply

We could make it more intuitive by attributing a starting value to the gas-fired power plants:

![afbeelding](https://user-images.githubusercontent.com/74194356/120329062-c13c7500-c2eb-11eb-98a6-a91916ee6abf.png)

In this way something does change when increasing solar or wind, the downside being that you start with some electricity supply.

Furthermore, the solar panels slider seems to represent all solar panels but it actually only represents solar panels on household rooftops. We could mention this within the title or within the description of the slider.

**Comment by ChaelKruip** [comment]
> We could make it more intuitive by attributing a starting value to the gas-fired power plants

Although I agree with your point that this is confusing, initialising the sliders on zero has been a conscious decision (it used to be like you suggest but with all existing power plants present).

> Furthermore, the solar panels slider seems to represent all solar panels but it actually only represents solar panels on household rooftops. We could mention this within the title or within the description of the slider.

Good point!
